# Generated by Django 2.2.1 on 2019-09-25 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='goods_price',
            field=models.FloatField(default=10, verbose_name='商品单价'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Saller.Goods', verbose_name='商品表'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.PayOrder', verbose_name='订单表外键'),
        ),
    ]
