# Generated by Django 2.2.1 on 2019-09-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0005_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='goods_delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
