# Generated by Django 2.2.1 on 2019-09-27 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0006_auto_20190927_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='goods_delete',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
    ]
