# Generated by Django 2.2.1 on 2019-09-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0007_auto_20190927_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_number',
            field=models.CharField(default=0, max_length=32),
        ),
        migrations.AlterField(
            model_name='payorder',
            name='order_status',
            field=models.IntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '待发货'), (3, '待收货'), (4, '完成'), (5, '拒收')], verbose_name='订单状态'),
        ),
    ]
