# Generated by Django 2.2.1 on 2019-09-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='type_picture',
            field=models.ImageField(default='img/01.jpg', upload_to='img'),
            preserve_default=False,
        ),
    ]
